name: build python
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - venv-patch-3.10
    paths:
      - python/3.10
jobs:
  push_to_registries:
    name: "python_3.10"
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            pwnbroker2499/python_3.10
            ghcr.io/pwnbroker2499/yolks
      
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./python/
          file: ./python/3.10/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            pwnbroker2499/python_3.10:venv
            ghcr.io/pwnbroker2499/venv
          labels: ${{ steps.meta.outputs.labels }}
# Using Pterodactyl's workflow for my github
